export const MRT_Localization_KO_CUSTOM = {
    actions: '수정/삭제',
    and: 'and',
    cancel: 'Cancel',
    changeFilterMode: 'Change filter mode',
    changeSearchMode: 'Change search mode',
    clearFilter: 'Clear filter',
    clearSearch: 'Clear search',
    clearSort: 'Clear sort',
    clickToCopy: 'Click to copy',
    collapse: 'Collapse',
    collapseAll: 'Collapse all',
    columnActions: '컬럼 설정',
    copiedToClipboard: 'Copied to clipboard',

    dropToGroupBy: 'Drop to group by {column}',
    edit: 'Edit',
    expand: 'Expand',
    expandAll: 'Expand all',
    filterArrIncludes: 'Includes',
    filterArrIncludesAll: 'Includes all',
    filterArrIncludesSome: 'Includes',
    filterBetween: 'Between',
    filterBetweenInclusive: 'Between Inclusive',
    filterByColumn: 'Filter by {column}',
    filterContains: '포함',
    filterEmpty: 'Empty',
    filterEndsWith: 'Ends With',
    filterEquals: 'Equals',
    filterEqualsString: 'Equals',
    filterFuzzy: 'Fuzzy',
    filterGreaterThan: 'Greater Than',
    filterGreaterThanOrEqualTo: 'Greater Than Or Equal To',
    filterInNumberRange: 'Between',
    filterIncludesString: '포함',
    filterIncludesStringSensitive: '포함',
    filterLessThan: 'Less Than',
    filterLessThanOrEqualTo: 'Less Than Or Equal To',
    filterMode: 'Filter Mode: {filterType}',
    filterNotEmpty: 'Not Empty',
    filterNotEquals: 'Not Equals',
    filterStartsWith: 'Starts With',
    filterWeakEquals: 'Equals',
    filteringByColumn: '{column} - {filterType} {filterValue} 로 필터',
    goToFirstPage: 'Go to first page',
    goToLastPage: 'Go to last page',
    goToNextPage: 'Go to next page',
    goToPreviousPage: 'Go to previous page',
    grab: 'Grab',
    groupByColumn: 'Group by {column}',
    groupedBy: 'Grouped by ',
    hideAll: '모두 감추기',
    hideColumn: 'Hide {column} column',
    max: 'Max',
    min: 'Min',
    move: 'Move',
    noRecordsToDisplay: 'No records to display',
    noResultsFound: 'No results found',
    of: 'of',
    or: 'or',
    pinToLeft: 'Pin to left',
    pinToRight: 'Pin to right',
    resetColumnSize: 'Reset column size',
    resetOrder: 'Reset order',
    rowActions: 'Row Actions',
    rowNumber: '#',
    rowNumbers: 'Row Numbers',
    rowsPerPage: '',
    save: 'Save',
    search: 'Search',
    selectedCountOfRowCountRowsSelected:
        '{rowCount} 개중 {selectedCount} 개 행이 선택되었습니다.',
    select: '선택',
    showAll: '모두 보기',
    showAllColumns: 'Show all columns',
    showHideColumns: '컬럼 보기/감추기',
    showHideFilters: '컬럼 검색 기능을 켜거나 끕니다.',
    showHideSearch: 'Show/Hide search',
    sortByColumnAsc: '"{column}" 오름차순',
    sortByColumnDesc: '"{column}" 내림차순',
    sortedByColumnAsc: '"{column}" 오름차순',
    sortedByColumnDesc: '"{column}" 내림차순',
    thenBy: ', then by ',
    toggleDensity: '스크린 밀도',
    toggleFullScreen: 'Toggle full screen',
    toggleSelectAll: '전체 선택/해제',
    toggleSelectRow: '1행 선택/해제',
    toggleVisibility: 'Toggle visibility',
    ungroupByColumn: 'Ungroup by {column}',
    unpin: 'Unpin',
    unpinAll: 'Unpin all',
};
